apiVersion: v1
kind: Service
metadata:
  name: backend
  spec:
    type: ClusterIP
    selector:
      tier: backend
      app: dice
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080